module.exports = function define() {
    this.ACTION_LOGIN = '101';
    this.ACTION_VERIFY = '102';
    this.ACTION_INSERT = '103';
    this.ACTION_QUERY = '104';
    this.RESULT_FAILED = '400';
    this.RESULT_SUCCESS = '200';
    this.RESULT_REDIRECT = '302';
    this.NOT_FOUND = '404';
    this.RESULT_PERMISSION_DENY = '401';
    this.RESULT_SERVER_FAILED = '402';
    this.RESULT_LOGIN_REQUESTED = '403';
    this.RESULT_ADD_NONE = '405';
    this.RESULT_EMPTY = '406';
    this.RESULT_DELETE_FAILED = '407';
    this.RESULT_UPDATE_FAILED = '408';
    this.SERVER_FAILED = '500';
    this.VALID_SUCCESS = '600';
    this.VALID_LACK_PARAM = '601';
    this.VALID_PARAM_TYPE_ERROR = '602';
    this.LOGIN_LACK_PARAM_USERNAME = '1001';
    this.LOGIN_LACK_PARAM_PWD = '1002';
    this.LACK_PARAM_SERVICEID = '1003';
    this.LOGIN_WORNG_PWD = '1003';
    this.LOGIN_SUCCESS = '1004';
}
